training:
  iters: 10000000
  sample_iters: 1000
  save_iters: 100000
  ema_rate: 0.99
  teacher_path: 'ckpts/checkerboard.pt'
  resume: False

data:
  type: '2d' #['2d', 'grey', 'rgb']
  dim: &dim 2
  train_batch: 1000
  test_batch: 1000
  num_workers: 4
  n_toy_samples: 100000
  rescale: False

score_net:
  model_type: 'MLP' #['MLP', 'UNet']
  dim: *dim
  # hidden_dim: [128, 256, 512, 1024, 512, 256, 128]
  hidden_dim: [64, 256, 1024, 256, 64]
  dropout_p: 0.1

optimizer:
  type: 'Adam' # ['Adam']
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.0001
  beta1: 0.9
  amsgrad: False
  eps: 0.00000001