training:
  iters: 5000000
  sample_iters: 10000
  save_iters: 100000
  ema: True
  ema_rate: 0.9999
  resume: True
  resume_path: '/home/jiachun/codebase/diffusion_playground/experiments/cifar_new_240207-10:14:02/checkpoints/cifar10.pt'
  # resume_path: '/home/jiachun/codebase/diffusion_playground/experiments/cifar_ema_240203-14:51:16/checkpoints/cifar10.pt'


data:
  root: './data'
  type: 'rgb' #['2d', 'grey', 'rgb']
  img_size: 32
  train_batch: 100
  test_batch: 100
  num_workers: 4
  rescale: True

score_net:
  model_type: 'UNet' #['MLP', 'UNet']
  in_channels: 3
  model_channels: 128
  out_channels: 3
  num_res_blocks: 2
  attention_resolutions: [16, ]
  dropout: 0.1

optimizer:
  type: 'Adam' # ['Adam']
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.0002
  beta1: 0.9
  amsgrad: False
  eps: 0.00000001